name: tbh
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - torchvision>=0.9.0
  - cudatoolkit=11.3  # CUDA 버전은 시스템에 맞게 조정하세요
  - numpy>=1.19.2
  - pip
  - tqdm  # 학습 진행률 표시를 위해 추가
  - matplotlib  # 결과 시각화를 위해 추가
  - tensorboard  # 학습 모니터링을 위해 추가
  - scikit-learn  # 평가 메트릭을 위해 추가
  - pip:
    - opencv-python  # 이미지 처리를 위해 추가 